version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data
    # ports:
    #   - 9003:9003

  web:
    image: nginx:1.20-alpine
    ports:
      - 8083:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    image: postgres:latest
    # build: ./infra/mysql
    ports:
      - 3333:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
